#!/usr/bin/env python3
"""
Create energy generation potential visualizations.

Graphs showing:
1. Cumulative capacity by drilling depth
2. Capacity by depth bin with breakdown
"""
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path

PLOT_DIR = Path("plots")
PLOT_DIR.mkdir(exist_ok=True)

# Match the original color scheme
COLORS = {
    "≤4 km": "#08306B",
    "4-5 km": "#2171B5",
    "5-6 km": "#00B050",
    "6-7 km": "#FFE100",
    "7-8 km": "#FF8C00",
    "8-10 km": "#E31A1C",
    ">10 km": "#DDDDDD"
}

# Capacity + area read from the energy analysis output (single source of truth,
# regenerated by calculate_energy_potential.py). Never hardcode these.
BINS = ["≤4 km", "4-5 km", "5-6 km", "6-7 km", "7-8 km", "8-10 km", ">10 km"]

_energy = pd.read_csv("data/processed/energy_generation_potential.csv").set_index("depth_bin")
CAPACITY_BY_DEPTH = {b: (round(_energy.loc[b, "capacity_typical_mw"] / 1000, 1) if b in _energy.index else 0)
                     for b in BINS}
AREA_BY_DEPTH = {b: (int(_energy.loc[b, "area_km2"]) if b in _energy.index else 0) for b in BINS}
# Share of total CONUS area in the deepest (>10 km) bin, computed from data.
_deep_area_pct = 100 * AREA_BY_DEPTH[">10 km"] / sum(AREA_BY_DEPTH.values())

def create_cumulative_capacity_chart():
    """Bar chart showing capacity by individual depth bin - ALL 7 bins."""
    fig, ax = plt.subplots(figsize=(16, 9))

    x_pos = np.arange(len(BINS))
    capacities = [CAPACITY_BY_DEPTH[b] for b in BINS]
    colors = [COLORS[b] for b in BINS]

    # Create bars
    bars = ax.bar(x_pos, capacities, color=colors,
                   edgecolor='black', linewidth=2, alpha=0.9, width=0.7)

    # Add US total capacity reference line
    us_total = 1287
    ax.axhline(y=us_total, color='red', linestyle='--', linewidth=2.5,
               label=f'US Total Capacity ({us_total:,} GW)', zorder=5, alpha=0.8)

    # Add capacity values on bars
    for i, (bar, cap, bin_name) in enumerate(zip(bars, capacities, BINS)):
        height = bar.get_height()

        if cap == 0:
            continue

        if height > us_total * 2:  # Tall bars - text inside
            y_pos = height * 0.5
            text_color = 'white' if bin_name != ">10 km" else 'black'
            va = 'center'
        else:  # Short bars - text above
            y_pos = height
            text_color = 'black'
            va = 'bottom'

        # Format capacity
        if cap >= 1000:
            cap_str = f'{cap/1000:.1f}K GW'
        else:
            cap_str = f'{cap:.0f} GW'

        ax.text(bar.get_x() + bar.get_width()/2., y_pos,
                cap_str,
                ha='center', va=va, fontsize=11, fontweight='bold',
                color=text_color)

    ax.set_ylabel('Generation Capacity (GW)', fontsize=14, fontweight='bold')
    ax.set_xlabel('Depth to 300°C', fontsize=14, fontweight='bold')
    ax.set_title('Geothermal Energy Potential by Depth — All 7 Bins\n'
                 'Conterminous United States — Typical Development (20% of area, 35 MW/km²)',
                 fontsize=16, fontweight='bold', pad=15)
    ax.set_xticks(x_pos)
    ax.set_xticklabels(BINS, fontsize=12, fontweight='bold')
    ax.tick_params(axis='y', labelsize=11)
    ax.set_ylim(0, max(capacities) * 1.1)
    ax.legend(fontsize=12, loc='upper left')
    ax.grid(axis='y', alpha=0.3, linestyle='--')

    # Add note
    fig.text(0.5, 0.02,
             'Based on superhot geothermal (300-400°C) power density. IDDP-2 demonstrated 45 MW per well at 427°C. '
             'Each depth bin represents an independent drilling target.',
             ha='center', fontsize=10, style='italic', color='#555', wrap=True)

    plt.tight_layout(rect=[0, 0.05, 1, 1])
    out = PLOT_DIR / "energy_potential_by_drilling_depth.png"
    plt.savefig(out, dpi=200, bbox_inches='tight', facecolor='white')
    plt.close()
    print(f"✅ Saved: {out}")


def create_stacked_capacity_chart():
    """Stacked bar showing capacity contribution by depth bin."""
    fig, ax = plt.subplots(figsize=(12, 10))

    # All 7 bins (exclude ≤4 km since it's 0)
    bins_show = ["4-5 km", "5-6 km", "6-7 km", "7-8 km", "8-10 km", ">10 km"]
    caps = [CAPACITY_BY_DEPTH[b] for b in bins_show]
    colors_show = [COLORS[b] for b in bins_show]

    total_cap = sum(caps)

    # Create pie chart
    wedges, texts, autotexts = ax.pie(caps, labels=bins_show,
                                       colors=colors_show,
                                       autopct=lambda pct: f'{pct:.1f}%' if pct > 1 else '',
                                       startangle=90, textprops={'fontsize': 12, 'fontweight': 'bold'})

    # Make wedges have black borders
    for w in wedges:
        w.set_edgecolor('black')
        w.set_linewidth(2)

    ax.set_title(f'Geothermal Capacity Distribution by Depth\nTotal: {total_cap:,.0f} GW',
                  fontsize=16, fontweight='bold', pad=20)

    fig.suptitle('Conterminous United States — All Depth Bins',
                 fontsize=14, y=0.98)

    fig.text(0.5, 0.02,
             f'>10 km resources represent {_deep_area_pct:.1f}% of CONUS area. '
             f'Superhot to supercritical resources (300-400°C) at all depths. US Total Capacity: 1,287 GW.',
             ha='center', fontsize=10, style='italic', color='#555')

    plt.tight_layout(rect=[0, 0.04, 1, 0.96])
    out = PLOT_DIR / "energy_capacity_distribution.png"
    plt.savefig(out, dpi=200, bbox_inches='tight', facecolor='white')
    plt.close()
    print(f"✅ Saved: {out}")


def main():
    print("Creating energy generation visualizations...")
    create_cumulative_capacity_chart()
    create_stacked_capacity_chart()
    print("\n✅ All visualizations complete!")

if __name__ == "__main__":
    main()
